"""
Kernel module code generation backend.

Emits a Linux kernel module (.c file) that can be compiled with kbuild:
  make -C /lib/modules/$(uname -r)/build M=$(pwd) modules

Uses printk for output, kernel memory allocation, and module_init/module_exit
macros. The generated code is GPL-licensed as required by the kernel.

NOTE: Kernel modules cannot use the C standard library. The runtime header
detects __KERNEL__ and provides kernel-compatible implementations.
"""

from __future__ import annotations

from .base import CodegenBackend, _escape_c


class KernelBackend(CodegenBackend):
    """Generate a Linux kernel module."""

    def file_header(self) -> list[str]:
        return [
            "/* Generated by scratch2c — https://github.com/scratch2c/scratch2c */",
            "/* Target: Linux kernel module */",
            "",
            "#include <linux/init.h>",
            "#include <linux/module.h>",
            "#include <linux/kernel.h>",
            "#include <linux/string.h>",
            '#include "scratch_runtime.h"',
            "",
            'MODULE_LICENSE("GPL");',
            'MODULE_AUTHOR("scratch2c");',
            'MODULE_DESCRIPTION("Scratch project compiled to kernel module");',
        ]

    def file_footer(self) -> list[str]:
        return [
            "module_init(scratch_init);",
            "module_exit(scratch_exit);",
        ]

    def emit_say(self, expr_code: str, is_string: bool) -> str:
        if is_string:
            return f'printk(KERN_INFO "%s\\n", {expr_code});'
        return f'printk(KERN_INFO "%ld\\n", (long){expr_code});'

    def main_function_name(self) -> str:
        return "scratch_init"

    def main_signature_open(self) -> str:
        return "static int __init scratch_init(void) {"

    def main_signature_close(self) -> str:
        return "return 0;"

    def exit_function_name(self) -> str:
        return "scratch_exit"

    def exit_signature_open(self) -> str:
        return "static void __exit scratch_exit(void) {"

    def exit_signature_close(self) -> str:
        return ""

    def declare_long_variable(self, c_name: str, initial: str) -> str:
        return f"static long {c_name} = {initial};"

    def declare_string_variable(self, c_name: str, initial: str) -> str:
        escaped = _escape_c(initial)
        return f'static char {c_name}[256] = "{escaped}";'

    def wait_comment(self, duration_code: str) -> str:
        return f"/* wait {duration_code} seconds — use msleep() if needed */"

    def emit_stop(self) -> str:
        # scratch_init returns int, not void — bare return won't compile
        return "return 0;"

    def _needs_exit(self) -> bool:
        # Kernel modules always need module_exit
        return True
