"""
Userspace code generation backend.

Emits a standalone C program that compiles with any C99 compiler:
  gcc -o program output.c

Uses printf for output, standard library for everything else.
The generated code includes scratch_runtime.h which provides
helper functions like scratch_join, scratch_ltoa, etc.
"""

from __future__ import annotations

from .base import CodegenBackend, _expr_type, _escape_c
from ..ir import ScratchType, Expression, Variable


class UserspaceBackend(CodegenBackend):
    """Generate a standalone userspace C program."""

    def file_header(self) -> list[str]:
        return [
            "/* Generated by scratch2c — https://github.com/scratch2c/scratch2c */",
            "/* Target: userspace (standalone C program) */",
            "",
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <string.h>',
            '#include "scratch_runtime.h"',
        ]

    def file_footer(self) -> list[str]:
        return []

    def emit_say(self, expr_code: str, is_string: bool) -> str:
        if is_string:
            return f'printf("%s\\n", {expr_code});'
        return f'printf("%ld\\n", (long){expr_code});'

    def main_function_name(self) -> str:
        return "main"

    def main_signature_open(self) -> str:
        return "int main(void) {"

    def main_signature_close(self) -> str:
        return "return 0;"

    def exit_function_name(self) -> str:
        return ""  # userspace doesn't need a separate exit function

    def exit_signature_open(self) -> str:
        return "void cleanup(void) {"

    def exit_signature_close(self) -> str:
        return ""

    def declare_long_variable(self, c_name: str, initial: str) -> str:
        return f"long {c_name} = {initial};"

    def declare_string_variable(self, c_name: str, initial: str) -> str:
        escaped = _escape_c(initial)
        return f'char {c_name}[256] = "{escaped}";'

    def wait_comment(self, duration_code: str) -> str:
        return f"/* wait {duration_code} seconds — no-op in userspace */"

    def _needs_exit(self) -> bool:
        return False
